### ISSUE TITLE
Plugin not working with MongoDB as Only Database

### ISSUE THREAD

**Issue by ratancs** [robertoschwald/grails-audit-logging-plugin#99]
http://stackoverflow.com/questions/31790839/grails-audit-plugin-not-working-with-mongodb

**Comment by robertoschwald** [comment]
Will fix asap

**Comment by robertoschwald** [comment]
Is fixed in latest 1.0.6-SNAPSHOT I published right now. Tested with Grails 2.4.4, mongodb 3.0.5 as only DS in a sample application.

Took a while as I never used mongodb before and had real issues getting mongodb working with authentication enabled. After I couldn't get it working this way, I decided to disable authentication in mongodb and remarked username / pw in the DataSource mongodb settings. 

Problem was, that the mongodb datastore does not hold a config property. 

Please try.

**Comment by robertoschwald** [comment]
Duplicate of #91

**Comment by bronoman** [comment]
Hi Robert,
thank you for the update. In general, it works. However, I can only audit INSERT events (from bootstrap or through controller). UPDATE events do not seem to be recognized by the plugin. These also do not show up in my mongoDB collection / table. 
Any idea why this is?
